### ISSUE TITLE
Need a update on this package with Authentication Flow with PKCE 

### ISSUE THREAD

**Issue by shameen3956** [Javaabu/EFaas-Socialite#6]
This package works with hybrid so need a update on using with  Authentication Flow with PKCE to make  more secure

**Comment by dash8x** [comment]
Upgrade to v2.0.0 and follow the instructions in the README on enabling PKCE. See if it works and let me know.

**Comment by shameen3956** [comment]
Yes after small study on last night Laravel Sociallite updated  socialite AbstractProvider file to enablePKCE $this->usesPKCE = false from true; and added         
updated getCodeFields with 
if ($this->usesPKCE()) {
            $fields['code_challenge'] = $this->getCodeChallenge();
            $fields['code_challenge_method'] = $this->getCodeChallengeMethod();
        }

works perfectly.

**Comment by shameen3956** [comment]
also thanks for updating repo so every one know  will how to use PKCE in this now

**Comment by shameen3956** [comment]
also when using PKCE  reponse_type should be only 'code'

**Comment by dash8x** [comment]
@shameen3956 did you test this package v2.0 without modifying the code?

**Comment by shameen3956** [comment]
will test 2.0 and will let know a update

**Comment by shameen3956** [comment]
yes its working with 2.0  for PKCE but have to update getCodeFields to ['response_type'] = 'code'; and commenting $fields['response_mode'] = 'form_post'; 

my suggestion on getCodeFields  is
    if ($this->usesPKCE()) {
//PKCE
            $fields['response_type'] = 'code';
            $fields['code_challenge'] = $this->getCodeChallenge();
            $fields['code_challenge_method'] = $this->getCodeChallengeMethod();
        }else{
//Hybrid
            $fields['response_mode'] = 'form_post';
            $fields['response_type'] = 'code id_token';
        }

also thanks for the update on repo

**Comment by dash8x** [comment]
What error do you get if you don't make that change?

**Comment by shameen3956** [comment]
if i uncomment     "'response_mode' => 'form_post'," 
Error
Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException
The POST method is not supported for this route. Supported methods: GET, HEAD. 

If i keep with id_token  'response_type' = 'code id_token' 
Error
Invalid grant type for client
(#11162)
